[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:loki]
command=loki -config.file %(ENV_STACK_CONFIG_DIR)s/loki.yaml
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

[program:tempo]
command=tempo -config.file=%(ENV_STACK_CONFIG_DIR)s/tempo.yaml
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

[program:prometheus]
command=prometheus --config.file=%(ENV_STACK_CONFIG_DIR)s/prometheus.yaml --web.enable-remote-write-receiver --web.enable-admin-api --enable-feature=exemplar-storage --storage.tsdb.path=/data/prometheus
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

[program:pushgateway]
command=pushgateway --web.listen-address=0.0.0.0:9091
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

[program:alertmanager]
command=alertmanager --config.file=%(ENV_STACK_CONFIG_DIR)s/alertmanager.yaml --storage.path=/data/alertmanager --web.external-url=http://localhost:6009/alertmanager --web.route-prefix=/
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

[program:otelcol]
command=otelcol-contrib --config=%(ENV_STACK_CONFIG_DIR)s/otel-collector.yaml
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:grafana]
command=/opt/grafana/bin/grafana server --homepath=/opt/grafana --config=%(ENV_STACK_CONFIG_DIR)s/grafana.ini
directory=/opt/grafana
environment=GF_PATHS_DATA="/data/grafana",GF_PATHS_PROVISIONING="%(ENV_STACK_CONFIG_DIR)s/grafana/provisioning",GF_SERVER_HTTP_PORT="3000"
autostart=true
autorestart=true
startsecs=10
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20

[program:envoy]
command=/bin/sh -c 'envoy -c "${ENVOY_CONFIG:-/etc/envoy/envoy.yaml}"'
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=30
